
gp_reg_64_to_32 = {"%rax": "%eax",
                   "%rcx": "%ecx",
                   "%rdx": "%edx",
                   "%rbx": "%ebx",
                   "%rsp": "%esp",
                   "%rbp": "%ebp",
                   "%rsi": "%esi",
                   "%rdi": "%edi",
                   "%r8": "%r8d",
                   "%r9": "%r9d",
                   "%r10": "%r10d",
                   "%r11": "%r11d",
                   "%r12": "%r12d",
                   "%r13": "%r13d",
                   "%r14": "%r14d",
                   "%r15": "%r15d",
                   }

gp_reg_32_to_16 = {"%eax": "%ax",
                   "%ecx": "%cx",
                   "%edx": "%dx",
                   "%ebx": "%bx",
                   "%esp": "%sp",
                   "%ebp": "%bp",
                   "%esi": "%si",
                   "%edi": "%di",
                   "%r8d": "%r8w",
                   "%r9d": "%r9w",
                   "%r10d": "%r10w",
                   "%r11d": "%r11w",
                   "%r12d": "%r12w",
                   "%r13d": "%r13w",
                   "%r14d": "%r14w",
                   "%r15d": "%r15w",
                   }

gp_reg_16_to_8 = {"%ax": "%al",
                   "%cx": "%cl",
                   "%dx": "%dl",
                   "%bx": "%bl",
                   "%sp": "%sil",
                   "%bp": "%bpl",
                   "%si": "%sil",
                   "%di": "%dil",
                   "%r8w": "%r8b",
                   "%r9dw": "%r9b",
                   "%r10w": "%r10b",
                   "%r11w": "%r11b",
                   "%r12w": "%r12b",
                   "%r13w": "%r13b",
                   "%r14w": "%r14b",
                   "%r15w": "%r15b",
                   }

gp_reg_8_to_None = {"%al": None,
                   "%cl": None,
                   "%dl": None,
                   "%bl": None,
                   "%sil": None,
                   "%bpl": None,
                   "%sil": None,
                   "%dil": None,
                   "%r8b": None,
                   "%r9b": None,
                   "%r10b": None,
                   "%r11b": None,
                   "%r12b": None,
                   "%r13b": None,
                   "%r14b": None,
                   "%r15b": None,
                   }

simd_reg_256_to_128 = {"%ymm0": "%xmm0",
                       "%ymm1": "%xmm1",
                       "%ymm2": "%xmm2",
                       "%ymm3": "%xmm3",
                       "%ymm4": "%xmm4",
                       "%ymm5": "%xmm5",
                       "%ymm6": "%xmm6",
                       "%ymm7": "%xmm7",
                       "%ymm8": "%xmm8",
                       "%ymm9": "%xmm9",
                       "%ymm10": "%xmm10",
                       "%ymm11": "%xmm11",
                       "%ymm12": "%xmm12",
                       "%ymm13": "%xmm13",
                       "%ymm14": "%xmm14",
                       "%ymm15": "%xmm15"}

simd_reg_128_to_None = {"%xmm0": None,
                        "%xmm1": None,
                        "%xmm2": None,
                        "%xmm3": None,
                        "%xmm4": None,
                        "%xmm5": None,
                        "%xmm6": None,
                        "%xmm7": None,
                        "%xmm8": None,
                        "%xmm9": None,
                        "%xmm10": None,
                        "%xmm11": None,
                        "%xmm12": None,
                        "%xmm13": None,
                        "%xmm14": None,
                        "%xmm15": None,
}

flags_to_none = {"%cf": None,
                 "%pf": None,
                 "%af": None,
                 "%zf": None,
                 "%sf": None,
                 "%tf": None,
                 "%if": None,
                 "%df": None,
                 "%of": None,
                 "%nt": None,
                 "%rf": None,
                 "%vm": None,
                 "%ac": None,
                 "%vif": None,
                 "%vip": None,
                 "%id": None}

LIVE_OUT_REGISTER_LIST = list(gp_reg_64_to_32.keys()) + list(simd_reg_256_to_128.keys()) + list(flags_to_none.keys())
DEF_IN_REGISTER_LIST = list(gp_reg_64_to_32.keys()) + list(simd_reg_256_to_128.keys()) + list(flags_to_none.keys())

NEXT_REGISTER_TESTING_DICT = {**gp_reg_64_to_32, **gp_reg_32_to_16, **gp_reg_16_to_8, **gp_reg_8_to_None,
                              **simd_reg_256_to_128, **simd_reg_128_to_None, **flags_to_none}
